### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by JorgeNachtigall** [Josedn/battleball_avatarimager#1]
Hi Josedn!

First of all I want to congrats you, bobba.io is a beautiful project.

I started doing my own version of habbo hotel, nothing that big like yours, but i'm finding a lot of trouble to find good images from the avatars, so I've found your repo. Could you provide some example of usage? I've tried a couple of things but I don't get it how to make this work.

Thanks and again, your project is amazing!

**Comment by JorgeNachtigall** [comment]
To be more clear, I got this:

```
[Wed Jan  8 19:54:48 2020] ::1:53558 [200]: /
[Wed Jan  8 19:54:48 2020] ::1:53559 [404]: /resource/map.json - No such file or directory
[Wed Jan  8 19:54:48 2020] ::1:53561 [404]: /resource/partsets.json - No such file or directory
[Wed Jan  8 19:54:48 2020] ::1:53560 [404]: /resource/figuredata.json - No such file or directory
[Wed Jan  8 19:54:48 2020] ::1:53562 [404]: /resource/draworder.json - No such file or directory
[Wed Jan  8 19:54:48 2020] ::1:53563 [404]: /resource/animation.json - No such file or directory
[Wed Jan  8 19:54:48 2020] ::1:53564 [404]: /favicon.ico - No such file or directory
```

So where I find those missing files?

Thanks!

**Comment by Josedn** [comment]
Thank you Jorge!

You can dump those files from Habbo.com with the _**resource_update.php**_ script.
Also you can download all the assets from here [http://images.bobba.io/images.zip](http://images.bobba.io/images.zip).
And if you're curious, you can check this article [http://forum.ragezone.com/f353/bobba-io-typescript-pixijs-react-1168855/](http://forum.ragezone.com/f353/bobba-io-typescript-pixijs-react-1168855/)

**Comment by JorgeNachtigall** [comment]
Hi @Josedn !

Thanks so much for you attention! This will help me a lot. =)

Again, thanks for taking time for answer me and congrats on your project!

Cheers!

**Comment by JorgeNachtigall** [comment]
Hi @Josedn !

Sorry for bothering you again with this thread.

Turns out that I'm lost all my computer files due to a HDD failure and don't have the assets anymore.

At the same time, I can't manage the resource_updage.php to work.

```
PHP Warning:  ob_start(): function 'mb_output_handler' not found or invalid function name in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 100
[Sat Jan  9 16:50:51 2021] PHP Notice:  ob_start(): failed to create buffer in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 100
[Sat Jan  9 16:50:51 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 109
[Sat Jan  9 16:50:51 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 115
[Sat Jan  9 16:50:51 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 109
[Sat Jan  9 16:50:51 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 109
[Sat Jan  9 16:50:51 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 109
[Sat Jan  9 16:50:51 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 115
[Sat Jan  9 16:50:51 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 109
[Sat Jan  9 16:50:51 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 115
[Sat Jan  9 16:50:51 2021] PHP Warning:  mkdir(): No such file or directory in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 126
[Sat Jan  9 16:50:51 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 109
[Sat Jan  9 16:50:52 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 109
[Sat Jan  9 16:50:52 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 115
[Sat Jan  9 16:50:52 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 109
[Sat Jan  9 16:50:52 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 115
[Sat Jan  9 16:50:52 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 109
[Sat Jan  9 16:50:52 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 109
[Sat Jan  9 16:50:52 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 115
[Sat Jan  9 16:50:52 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 109
[Sat Jan  9 16:50:52 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 115
[Sat Jan  9 16:50:52 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 109
[Sat Jan  9 16:50:52 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 109
[Sat Jan  9 16:50:52 2021] PHP Notice:  ob_flush(): failed to flush buffer. No buffer to flush in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 115
[Sat Jan  9 16:50:52 2021] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php:493
Stack trace:
#0 /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php(776): ExtractFigureData('http://localhos...')
#1 {main}
  thrown in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 493
[Sat Jan  9 16:50:52 2021] 127.0.0.1:45348 [200]: /resource_update.php - Uncaught Error: Call to undefined function simplexml_load_string() in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php:493
Stack trace:
#0 /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php(776): ExtractFigureData('http://localhos...')
#1 {main}
  thrown in /home/jorge/Documents/Projects/bobba_avatarimager-master/resource_update.php on line 493
```
At the same time, I noticed that your zip link is not working anymore too:  http://images.bobba.io/images.zip

Could you provide me any help?

Thanks!

**Comment by JorgeNachtigall** [comment]
Ok, I managed it to work, I've never worked with php so I'm really newbie.

The problem is now that the swf url is no more accessible (probably due to the recently changes in the game).

Habbo SWF figure resource dump Tool

```
OFFICIAL RESOURCE URL : https://www.habbo.com/

FLASH CLIENT URL      : https://images.habbo.com/gordon/PRODUCTION-201711211204-412329988/

OUTPUT PATH           : C:\wamp64\www\bobba/resource/

Extract SWF: Habbo.swf

Download: https://images.habbo.com/gordon/PRODUCTION-201711211204-412329988/Habbo.swf

Error: file_get_contents(https://images.habbo.com/gordon/PRODUCTION-201711211204-412329988/Habbo.swf): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

Extract FigureMap

Download: https://images.habbo.com/gordon/PRODUCTION-201711211204-412329988/figuremap.xml

Error: file_get_contents(https://images.habbo.com/gordon/PRODUCTION-201711211204-412329988/figuremap.xml): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

Extract FigureData

Download: http://localhost/figuredata.xml

Error: file_get_contents(http://localhost/figuredata.xml): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
```


So, do you still have the .zip file to share?

Thanks!

**Comment by Josedn** [comment]
Hello, you can get those updated urls from habbo.com legacy client, also check external_variables

Here is the updated link... i'll try to get in .zip shortly [https://images.bobba.io/images.tar.gz](https://images.bobba.io/images.tar.gz)

**Comment by JorgeNachtigall** [comment]
Thanks for the response, I'll keep this file safe now for not bothering you in the future hahah

Cheers
